/*
 * 
 --------------------------------- Part A ---------------------------------
 Q1

   1- .csproj => containing project info about the sdk used , target framework , packages version
                  is nulable enabled or not , is implicitly using used or not and is the project is executable or not 

   2- Program.cs => this file contains code inwhich my project execution stats from 

   3- bin => contains IL files generated by roslyn complier (extensions are .dll and .exe (if the project is executable))

   4- obj => cashes the last state my project reached so if i add any new feature and want to build again 
             it's not building from zero it builds from last state the project stopped 
 

Q2 => The project .csprog file contents copied and pasted in ANSWERS.md file


Q3 => i have used ; with the namespace so it indicates that the file is file scoped namespace which meaning that
      all code below in that file belongs to this namespace without using braces, so it removes level of indentation.


Q4 =>  My project uses the newer .slnx not .sln because it's more easer, readable , maintainable and 
       could be edited manually but on the other hand .sln is also has many advantages like it is
       used or more suitable with older versions of tools and visual studio and this .sln is widely support 
 
 
 */
using CSharpBasicsAssignment;


// ---------- Part B test ------------
Console.WriteLine(" -------------------- Part B ------------------------");

PartBDemo.RunTypesDemo();



// ----------- Part C test -----------
//Experiment 1

Console.WriteLine(" -------------------- Part C ------------------------");
Console.WriteLine(" #Experiment 1 ");
Point p1 = new Point()
{
    x = 1,
    y = 2
};

Point p2 = p1;
p2.x = 99;

Console.WriteLine("P1.x = " + p1.x);
Console.WriteLine("P2.x = " + p2.x);

// The values Diferent because struct is a value type so when assign p1 to p2
// the value of p1 copied into p2 not the reference 


// #Experiment 2

Console.WriteLine(" #Experiment 2");
Order o1 = new Order()
{
    OrderId = 1,
    CustomerName = "Marwan",
    ItemCode = 12348768,
    Quantity = 2,
    UnitPrice = 250.25m,
    DiscountPercent = 25,
    ShippingCity = "Alex",
    Priority = 'H',


};

Order o2 = o1;
o2.IsPaid = true;
//the result from the comming two lines is the same because when we assign o1 to o2 we copy the reference stored in o1 to o2
//  so the two reference variabales poit to the same object in heap 
// so any change in the object state from anyone of references will be visible through the other reference

Console.WriteLine("IsPaid from O1 => " + o1.IsPaid);
Console.WriteLine("IsPaid from O2 => " + o2.IsPaid);

object boxedOrder = o1;
Order o3 = (Order)boxedOrder; // casting because we can't store reference into order type
Console.WriteLine("Is o1 and o3 have the same reference => " + Object.ReferenceEquals(o1, o3));
o2.PrintSummary();

Console.WriteLine("\n value type variables store thier values directly while reference type store a reference to an object which lives in heap ");
Console.WriteLine("when assign a value type the actual value is copied but when assigning a reference type the reference is copied so that both variables point to the same object in heap ");
Console.WriteLine("storing reference type to an object variable it not creating a new object is create another reference to the same object");

// -----------------------------------


// ----------- Part D test -----------

Console.WriteLine(" -------------------- Part D ------------------------");
Console.WriteLine(" #D 1 ");
Program.method1();
Program.method2();
Console.WriteLine(" #D 2 ");
Program.CompoundAssignment();
Console.WriteLine(" #D 3 ");
Program.BitWiseOperators();


// ------------ Part F test -----------

Console.WriteLine(" \n -------------------- Part F ------------------");
int[] nums1 = { 4, 1, 2, 1, 2 };
int[] nums2 = { 1, 10, 20, 10, 20 };
SingleNumber s1 = new SingleNumber();
Console.WriteLine(s1.FindSingleNumber(nums1));
Console.WriteLine(s1.FindSingleNumber(nums2));
//-----------------------------------




// ------------- Part B ---------------

class PartBDemo
{

    public static void RunTypesDemo()
    {

        Console.WriteLine("---------- Step 1 --------------");
        int intValue = 42;
        long longValue = 100000L;
        double doubleValue = 3.14;
        decimal decimalValue = 99.99m;
        bool boolValue = true;
        char charValue = 'A';
        string stringValue = "Hello";
        var varValue = 123;

        Console.WriteLine($"int: {intValue}, Type: {intValue.GetType()}");
        Console.WriteLine($"long: {longValue}, Type: {longValue.GetType()}");
        Console.WriteLine($"double: {doubleValue}, Type: {doubleValue.GetType()}");
        Console.WriteLine($"decimal: {decimalValue}, Type: {decimalValue.GetType()}");
        Console.WriteLine($"bool: {boolValue}, Type: {boolValue.GetType()}");
        Console.WriteLine($"char: {charValue}, Type: {charValue.GetType()}");
        Console.WriteLine($"string: {stringValue}, Type: {stringValue.GetType()}");
        Console.WriteLine($"var: {varValue}, Type: {varValue.GetType()}");

        Console.WriteLine("---------- Step 2 --------------");
        int integerValue = 25;
        // this line is possible because :- 
        // 1- the left side is smaller than the right side
        // 2- two data types has the same representation 
        long lvalue = integerValue;
        char x = 'a';
        int y = x; // this line will work and implicitly the compilder will put the asci code of character 'a'

        Console.WriteLine("---------- Step 3 --------------");

        double number = 10.8;

        int castResult = (int)number;
        int convertResult = Convert.ToInt32(number);

        Console.WriteLine($"Original double value: {number}");
        Console.WriteLine($"Using (int): {castResult}");
        Console.WriteLine($"Using Convert.ToInt32(): {convertResult}");

        // Casting with (int) truncates the decimal part,
        // while Convert.ToInt32() rounds the value to the nearest integer.

        Console.WriteLine("---------- Step 4 --------------");

        int number2 = 5;
        double number3 = 5.0;
        Console.WriteLine($" dividing 5 / 2: {number2 / 2}"); // this will truncate the decimal part
        Console.WriteLine($"dividing 5.0 / 2: {number3 / 2}");


        Console.WriteLine("---------- Step 5 --------------");

        int regularInt = 5;
        Console.WriteLine($"regular integer without boxing: {regularInt}");
        object boxed = regularInt;
        Console.WriteLine($"Boxing: {boxed}");
        int unboxed = (int)boxed;
        Console.WriteLine($"unboxing: {unboxed}");


        Console.WriteLine("---------- Step 6 --------------");

        string s1 = "42";
        string s2 = "abc"; // bad format
        Console.WriteLine($"reading 42 with int.parse: {int.Parse(s1)}");
        bool isSucceed = int.TryParse(s2, out int val);
        if (!isSucceed)
        {
            Console.WriteLine($"Coudn't parse {s2}");
        }
        else
        {
            Console.WriteLine("parsed val is = " + val);
        }


        Console.WriteLine("---------- Step 7 --------------");

        float f1 = 55.66f;
        // decimal d1 = f1;  this line will throw an error because both of them represent numbers in different way
        // as float represent numbers with base 2 and decimal with base 10
        // but if we used explicit conversion it will work
        decimal d1 = Convert.ToDecimal(f1);
        Console.WriteLine($"the floating number 55.66f after explicit conversion =  {d1}");


    }

}



// ------------- Part D ---------------

partial class Program
{
    // ------- D1 -------
    // (field scope)
    private static int x = 100;

    //Method scope
    public static void method1()
    {
        int x = 33;

    }

    //Block scope
    public static void method2()
    {
        for (int i = 0; i < 3; i++)
        {
            int insideLoop = i * 3;
            Console.WriteLine($"{i} in loop , insideLoop = {insideLoop}");
        }

        // Console.WriteLine(i); 
        //this line will obtains a copile error because i and insideLoop are only visible inside the loop block.
    }

    // D2

    public static void CompoundAssignment()
    {
        int total = 100;

        total += 5;
        Console.WriteLine($"After += 5: {total}");

        total -= 10;
        Console.WriteLine($"After -= 10: {total}");

        total *= 2;
        Console.WriteLine($"After *= 2: {total}");

        total /= 5;
        Console.WriteLine($"After /= 5: {total}");

        total %= 7;
        Console.WriteLine($"After %= 7: {total}");


        // Compound assignment:
        // total += 5;
        // is equivalent to:
        // total = total + 5;
    }


    // D3
    public static void BitWiseOperators()
    {
        int a = 12; //1100
        int b = 10; //1010


        Console.WriteLine($"a & b = {a & b}");
        Console.WriteLine($"a | b = {a | b}");
        Console.WriteLine($"a ^ b = {a ^ b}");

        /*
            Binary calculations:

            a = 12 = 1100
            b = 10 = 1010

            AND (&):
              1100
              1010
              ----
              1000 = 8

            OR (|):
              1100
              1010
              ----
              1110 = 14

            XOR (^):
              1100
              1010
              ----
              0110 = 6



        & is a bitwise operator works  bit by bit  on integers
        && is a logical operators works with conditions
        and if the left side in the condition is false:
        - with && will not continue and make the result false
        - with & will continue to check the right side

        */
    }





}


//-------------------------------------




// ----------- Part C ------------
struct Point
{
    public int x; public int y;
}


// ---------------- Part F -------------

public class SingleNumber
{

    //XOR-ing every number together help us to find the single appearence number in the array 
    // because XOR-ing duplicate numbers together cancel each other and XOR-ing any number with 0 
    // will not change the number so at the end of the xor-ing process we will find our target
    // 4^4 = 0 
    //4^0 = 4


    public int FindSingleNumber(int[] nums)
    {
        int result = 0;
        for (int i = 0; i < nums.Length; i++)
        {
            result ^= nums[i];
        }

        return result;
    }
}


